title: "REALMat"
subtitle: "Recursos Educacionais Abertos na Licenciatura em Matemática"
name: "REALMat"
description: "Recursos Educacionais Abertos na Licenciatura em Matemática"
url: "https://projetorealmat.github.io"
baseurl: ""
repository: "projetorealmat/projetorealmat.github.io"
books_catalog: "_data/books.json"
locale: "pt-BR"

search: true
future: false

include:
  - _pages
  - generated

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
